"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Scraper.py']
APP_NAME = "Scraper"
DATA_FILES = ['url-data.txt', 'README.md']
OPTIONS = {
    'argv_emulation': True,
    'packages': ['webbot'],
	'iconfile': 'scraper.icns',
	'plist': {
        'CFBundleName': APP_NAME,
        'CFBundleDisplayName': APP_NAME,
        'CFBundleGetInfoString': "General Purpose Automated Scraper",
        'CFBundleIdentifier': "com.nickjadams.osx.scraper",
        'CFBundleVersion': "0.0.1",
        'CFBundleShortVersionString': "0.0.1",
        'NSHumanReadableCopyright': u"Copyright © 2020, Nick Adams"
    }
}

setup(
	name=APP_NAME,
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
